insert into content (dtype, id, category, title, section_id) values ('section', 101, 'Tools', 'Legal', 116);
insert into content (dtype, id, category, title, section_id) values ('section', 102, 'Movies', 'Engineering', 165);
insert into content (dtype, id, category, title, section_id) values ('section', 103, 'Clothing', 'Training', 117);
insert into content (dtype, id, category, title, section_id) values ('section', 104, 'Electronics', 'Marketing', 107);
insert into content (dtype, id, category, title, section_id) values ('section', 105, 'Beauty', 'Business Development', 119);
insert into content (dtype, id, category, title, section_id) values ('section', 106, 'Industrial', 'Legal', 157);
insert into content (dtype, id, category, title, section_id) values ('section', 107, 'Outdoors', 'Accounting', 106);
insert into content (dtype, id, category, title, section_id) values ('section', 108, 'Industrial', 'Product Management', 106);
insert into content (dtype, id, category, title, section_id) values ('section', 109, 'Books', 'Human Resources', 127);
insert into content (dtype, id, category, title, section_id) values ('section', 110, 'Books', 'Engineering', 151);
insert into content (dtype, id, category, title, section_id) values ('section', 111, 'Shoes', 'Sales', 189);
insert into content (dtype, id, category, title, section_id) values ('section', 112, 'Music', 'Legal', 165);
insert into content (dtype, id, category, title, section_id) values ('section', 113, 'Garden', 'Sales', 115);
insert into content (dtype, id, category, title, section_id) values ('section', 114, 'Health', 'Marketing', 133);
insert into content (dtype, id, category, title, section_id) values ('section', 115, 'Sports', 'Legal', 188);
insert into content (dtype, id, category, title, section_id) values ('section', 116, 'Tools', 'Training', 173);
insert into content (dtype, id, category, title, section_id) values ('section', 117, 'Baby', 'Business Development', 128);
insert into content (dtype, id, category, title, section_id) values ('section', 118, 'Electronics', 'Legal', 167);
insert into content (dtype, id, category, title, section_id) values ('section', 119, 'Computers', 'Product Management', 154);
insert into content (dtype, id, category, title, section_id) values ('section', 120, 'Shoes', 'Product Management', 161);
insert into content (dtype, id, category, title, section_id) values ('section', 121, 'Garden', 'Business Development', 184);
insert into content (dtype, id, category, title, section_id) values ('section', 122, 'Electronics', 'Product Management', 144);
insert into content (dtype, id, category, title, section_id) values ('section', 123, 'Health', 'Research and Development', 140);
insert into content (dtype, id, category, title, section_id) values ('section', 124, 'Jewelry', 'Product Management', 107);
insert into content (dtype, id, category, title, section_id) values ('section', 125, 'Health', 'Accounting', 126);
insert into content (dtype, id, category, title, section_id) values ('section', 126, 'Tools', 'Engineering', 127);
insert into content (dtype, id, category, title, section_id) values ('section', 127, 'Health', 'Training', 122);
insert into content (dtype, id, category, title, section_id) values ('section', 128, 'Movies', 'Sales', 153);
insert into content (dtype, id, category, title, section_id) values ('section', 129, 'Garden', 'Accounting', 137);
insert into content (dtype, id, category, title, section_id) values ('section', 130, 'Beauty', 'Product Management', 115);
insert into content (dtype, id, category, title, section_id) values ('section', 131, 'Beauty', 'Research and Development', 133);
insert into content (dtype, id, category, title, section_id) values ('section', 132, 'Jewelry', 'Product Management', 163);
insert into content (dtype, id, category, title, section_id) values ('section', 133, 'Health', 'Support', 149);
insert into content (dtype, id, category, title, section_id) values ('section', 134, 'Sports', 'Services', 192);
insert into content (dtype, id, category, title, section_id) values ('section', 135, 'Electronics', 'Legal', 136);
insert into content (dtype, id, category, title, section_id) values ('section', 136, 'Baby', 'Accounting', 107);
insert into content (dtype, id, category, title, section_id) values ('section', 137, 'Shoes', 'Training', 184);
insert into content (dtype, id, category, title, section_id) values ('section', 138, 'Electronics', 'Research and Development', 106);
insert into content (dtype, id, category, title, section_id) values ('section', 139, 'Movies', 'Human Resources', 177);
insert into content (dtype, id, category, title, section_id) values ('section', 140, 'Automotive', 'Support', 132);
insert into content (dtype, id, category, title, section_id) values ('section', 141, 'Industrial', 'Product Management', 189);
insert into content (dtype, id, category, title, section_id) values ('section', 142, 'Baby', 'Business Development', 139);
insert into content (dtype, id, category, title, section_id) values ('section', 143, 'Baby', 'Sales', 186);
insert into content (dtype, id, category, title, section_id) values ('section', 144, 'Outdoors', 'Research and Development', 120);
insert into content (dtype, id, category, title, section_id) values ('section', 145, 'Health', 'Product Management', 149);
insert into content (dtype, id, category, title, section_id) values ('section', 146, 'Sports', 'Accounting', 194);
insert into content (dtype, id, category, title, section_id) values ('section', 147, 'Baby', 'Research and Development', 195);
insert into content (dtype, id, category, title, section_id) values ('section', 148, 'Books', 'Sales', 117);
insert into content (dtype, id, category, title, section_id) values ('section', 149, 'Movies', 'Human Resources', 185);
insert into content (dtype, id, category, title, section_id) values ('section', 150, 'Kids', 'Research and Development', 124);
insert into content (dtype, id, category, title, section_id) values ('section', 151, 'Music', 'Product Management', 140);
insert into content (dtype, id, category, title, section_id) values ('section', 152, 'Books', 'Product Management', 134);
insert into content (dtype, id, category, title, section_id) values ('section', 153, 'Outdoors', 'Engineering', 130);
insert into content (dtype, id, category, title, section_id) values ('section', 154, 'Movies', 'Sales', 133);
insert into content (dtype, id, category, title, section_id) values ('section', 155, 'Games', 'Research and Development', 185);
insert into content (dtype, id, category, title, section_id) values ('section', 156, 'Automotive', 'Engineering', 186);
insert into content (dtype, id, category, title, section_id) values ('section', 157, 'Music', 'Accounting', 126);
insert into content (dtype, id, category, title, section_id) values ('section', 158, 'Sports', 'Business Development', 200);
insert into content (dtype, id, category, title, section_id) values ('section', 159, 'Toys', 'Engineering', 112);
insert into content (dtype, id, category, title, section_id) values ('section', 160, 'Industrial', 'Services', 103);
insert into content (dtype, id, category, title, section_id) values ('section', 161, 'Garden', 'Sales', 138);
insert into content (dtype, id, category, title, section_id) values ('section', 162, 'Tools', 'Engineering', 142);
insert into content (dtype, id, category, title, section_id) values ('section', 163, 'Beauty', 'Marketing', 126);
insert into content (dtype, id, category, title, section_id) values ('section', 164, 'Computers', 'Research and Development', 155);
insert into content (dtype, id, category, title, section_id) values ('section', 165, 'Tools', 'Product Management', 148);
insert into content (dtype, id, category, title, section_id) values ('section', 166, 'Industrial', 'Research and Development', 184);
insert into content (dtype, id, category, title, section_id) values ('section', 167, 'Music', 'Research and Development', 113);
insert into content (dtype, id, category, title, section_id) values ('section', 168, 'Outdoors', 'Training', 123);
insert into content (dtype, id, category, title, section_id) values ('section', 169, 'Industrial', 'Training', 106);
insert into content (dtype, id, category, title, section_id) values ('section', 170, 'Clothing', 'Legal', 123);
insert into content (dtype, id, category, title, section_id) values ('section', 171, 'Games', 'Sales', 176);
insert into content (dtype, id, category, title, section_id) values ('section', 172, 'Toys', 'Support', 102);
insert into content (dtype, id, category, title, section_id) values ('section', 173, 'Clothing', 'Sales', 159);
insert into content (dtype, id, category, title, section_id) values ('section', 174, 'Games', 'Support', 187);
insert into content (dtype, id, category, title, section_id) values ('section', 175, 'Automotive', 'Human Resources', 139);
insert into content (dtype, id, category, title, section_id) values ('section', 176, 'Toys', 'Research and Development', 131);
insert into content (dtype, id, category, title, section_id) values ('section', 177, 'Toys', 'Marketing', 129);
insert into content (dtype, id, category, title, section_id) values ('section', 178, 'Garden', 'Services', 194);
insert into content (dtype, id, category, title, section_id) values ('section', 179, 'Grocery', 'Business Development', 200);
insert into content (dtype, id, category, title, section_id) values ('section', 180, 'Grocery', 'Legal', 114);
insert into content (dtype, id, category, title, section_id) values ('section', 181, 'Computers', 'Marketing', 195);
insert into content (dtype, id, category, title, section_id) values ('section', 182, 'Movies', 'Engineering', 153);
insert into content (dtype, id, category, title, section_id) values ('section', 183, 'Sports', 'Product Management', 144);
insert into content (dtype, id, category, title, section_id) values ('section', 184, 'Electronics', 'Human Resources', 120);
insert into content (dtype, id, category, title, section_id) values ('section', 185, 'Baby', 'Research and Development', 163);
insert into content (dtype, id, category, title, section_id) values ('section', 186, 'Electronics', 'Sales', 200);
insert into content (dtype, id, category, title, section_id) values ('section', 187, 'Books', 'Accounting', 173);
insert into content (dtype, id, category, title, section_id) values ('section', 188, 'Kids', 'Research and Development', 164);
insert into content (dtype, id, category, title, section_id) values ('section', 189, 'Sports', 'Services', 105);
insert into content (dtype, id, category, title, section_id) values ('section', 190, 'Clothing', 'Training', 104);
insert into content (dtype, id, category, title, section_id) values ('section', 191, 'Tools', 'Services', 189);
insert into content (dtype, id, category, title, section_id) values ('section', 192, 'Computers', 'Business Development', 168);
insert into content (dtype, id, category, title, section_id) values ('section', 193, 'Kids', 'Engineering', 126);
insert into content (dtype, id, category, title, section_id) values ('section', 194, 'Sports', 'Services', 142);
insert into content (dtype, id, category, title, section_id) values ('section', 195, 'Tools', 'Services', 164);
insert into content (dtype, id, category, title, section_id) values ('section', 196, 'Garden', 'Support', 192);
insert into content (dtype, id, category, title, section_id) values ('section', 197, 'Music', 'Marketing', 121);
insert into content (dtype, id, category, title, section_id) values ('section', 198, 'Garden', 'Accounting', 179);
insert into content (dtype, id, category, title, section_id) values ('section', 199, 'Garden', 'Accounting', 149);
insert into content (dtype, id, category, title, section_id) values ('section', 200, 'Home', 'Engineering', 166);
