insert into product (id, name, price) values (1, 'Soup - Campbells Beef Strogonoff', 99.2);
insert into product (id, name, price) values (2, 'Cookies - Oreo, 4 Pack', 7.29);
insert into product (id, name, price) values (3, 'Food Colouring - Green', 56.84);
insert into product (id, name, price) values (4, 'Chocolate - White', 36.88);
insert into product (id, name, price) values (5, 'Pate - Peppercorn', 58.18);
insert into product (id, name, price) values (6, 'Calvados - Boulard', 53.23);
insert into product (id, name, price) values (7, 'The Pop Shoppe - Grape', 75.09);
insert into product (id, name, price) values (8, 'Uniform Linen Charge', 54.52);
insert into product (id, name, price) values (9, 'Pork - Butt, Boneless', 36.97);
insert into product (id, name, price) values (10, 'Cranberries - Fresh', 61.45);
insert into product (id, name, price) values (11, 'Chocolate - Dark Callets', 7.27);
insert into product (id, name, price) values (12, 'Tea - Green', 8.28);
insert into product (id, name, price) values (13, 'Sherbet - Raspberry', 2.59);
insert into product (id, name, price) values (14, 'Flavouring Vanilla Artificial', 31.7);
insert into product (id, name, price) values (15, 'Wine - Cave Springs Dry Riesling', 35.29);
insert into product (id, name, price) values (16, 'Basil - Thai', 23.01);
insert into product (id, name, price) values (17, 'Pasta - Fett Alfredo, Single Serve', 89.13);
insert into product (id, name, price) values (18, 'Veal - Inside', 14.91);
insert into product (id, name, price) values (19, 'Rice - Brown', 26.61);
insert into product (id, name, price) values (20, 'Ham - Black Forest', 65.71);
insert into product (id, name, price) values (21, 'Eggplant - Regular', 90.22);
insert into product (id, name, price) values (22, 'Pie Filling - Cherry', 11.59);
insert into product (id, name, price) values (23, 'Pork - Bacon, Double Smoked', 6.87);
insert into product (id, name, price) values (24, 'Bread - Hot Dog Buns', 50.5);
insert into product (id, name, price) values (25, 'Tomatoes - Roma', 74.94);
insert into product (id, name, price) values (26, 'The Pop Shoppe - Black Cherry', 29.21);
insert into product (id, name, price) values (27, 'Table Cloth 54x54 Colour', 38.2);
insert into product (id, name, price) values (28, 'Sprouts - Corn', 57.61);
insert into product (id, name, price) values (29, 'Mints - Striped Red', 14.88);
insert into product (id, name, price) values (30, 'Wine - Champagne Brut Veuve', 52.55);
insert into product (id, name, price) values (31, 'Gin - Gilbeys London, Dry', 96.96);
insert into product (id, name, price) values (32, 'Strawberries', 99.94);
insert into product (id, name, price) values (33, 'Muffin Batt - Ban Dream Zero', 66.43);
insert into product (id, name, price) values (34, 'Flour - Whole Wheat', 20.45);
insert into product (id, name, price) values (35, 'Halibut - Fletches', 67.71);
insert into product (id, name, price) values (36, 'Juice - Lagoon Mango', 7.84);
insert into product (id, name, price) values (37, 'Bar - Sweet And Salty Chocolate', 34.55);
insert into product (id, name, price) values (38, 'Apple - Macintosh', 81.23);
insert into product (id, name, price) values (39, 'Pate Pans Yellow', 25.75);
insert into product (id, name, price) values (40, 'Island Oasis - Wildberry', 28.61);
insert into product (id, name, price) values (41, 'Pork Loin Cutlets', 71.5);
insert into product (id, name, price) values (42, 'Bread - Pita', 17.34);
insert into product (id, name, price) values (43, 'Bread - Bagels, Mini', 83.47);
insert into product (id, name, price) values (44, 'Wine - Winzer Krems Gruner', 53.29);
insert into product (id, name, price) values (45, 'Tomatoes - Grape', 99.85);
insert into product (id, name, price) values (46, 'Beets - Mini Golden', 72.68);
insert into product (id, name, price) values (47, 'Pear - Prickly', 95.14);
insert into product (id, name, price) values (48, 'Juice - Cranberry, 341 Ml', 91.04);
insert into product (id, name, price) values (49, 'Glucose', 31.52);
insert into product (id, name, price) values (50, 'Potato - Sweet', 23.3);
insert into product (id, name, price) values (51, 'Chocolate - White', 3.59);
insert into product (id, name, price) values (52, 'Shark - Loin', 31.52);
insert into product (id, name, price) values (53, 'Coffee - Flavoured', 3.99);
insert into product (id, name, price) values (54, 'Chicken Giblets', 99.19);
insert into product (id, name, price) values (55, 'Fish - Artic Char, Cold Smoked', 60.85);
insert into product (id, name, price) values (56, 'Fish - Halibut, Cold Smoked', 48.32);
insert into product (id, name, price) values (57, 'Wine - Fontanafredda Barolo', 29.02);
insert into product (id, name, price) values (58, 'Tea - Green', 22.79);
insert into product (id, name, price) values (59, 'Cinnamon - Ground', 85.03);
insert into product (id, name, price) values (60, 'Sobe - Tropical Energy', 41.84);
insert into product (id, name, price) values (61, 'Wine - Saint - Bris 2002, Sauv', 6.09);
insert into product (id, name, price) values (62, 'Spice - Chili Powder Mexican', 16.29);
insert into product (id, name, price) values (63, 'Foil Wrap', 96.36);
insert into product (id, name, price) values (64, 'Pasta - Penne, Lisce, Dry', 35.72);
insert into product (id, name, price) values (65, 'Pie Shell - 5', 14.95);
insert into product (id, name, price) values (66, 'Squash - Guords', 18.41);
insert into product (id, name, price) values (67, 'Table Cloth 54x72 Colour', 21.49);
insert into product (id, name, price) values (68, 'Juice - Grape, White', 62.5);
insert into product (id, name, price) values (69, 'Tea - Decaf Lipton', 46.24);
insert into product (id, name, price) values (70, 'Mix - Cocktail Strawberry Daiquiri', 32.95);
insert into product (id, name, price) values (71, 'Pastry - French Mini Assorted', 26.13);
insert into product (id, name, price) values (72, 'Dc - Sakura Fu', 50.99);
insert into product (id, name, price) values (73, 'Yogurt - French Vanilla', 32.68);
insert into product (id, name, price) values (74, 'Sauce - Gravy, Au Jus, Mix', 37.32);
insert into product (id, name, price) values (75, 'Soup - Campbells', 28.11);
insert into product (id, name, price) values (76, 'Stock - Chicken, White', 48.97);
insert into product (id, name, price) values (77, 'Energy Drink Red Bull', 78.23);
insert into product (id, name, price) values (78, 'Cocoa Powder - Dutched', 55.2);
insert into product (id, name, price) values (79, 'Papayas', 94.18);
insert into product (id, name, price) values (80, 'Chips Potato Salt Vinegar 43g', 48.12);
insert into product (id, name, price) values (81, 'Veal - Striploin', 88.01);
insert into product (id, name, price) values (82, 'Crab - Back Fin Meat, Canned', 75.74);
insert into product (id, name, price) values (83, 'Oven Mitts - 15 Inch', 96.2);
insert into product (id, name, price) values (84, 'Table Cloth - 53x69 Colour', 40.35);
insert into product (id, name, price) values (85, 'Wine - Magnotta - Belpaese', 34.98);
insert into product (id, name, price) values (86, 'Currants', 21.87);
insert into product (id, name, price) values (87, 'Venison - Racks Frenched', 17.69);
insert into product (id, name, price) values (88, 'Beer - Corona', 14.74);
insert into product (id, name, price) values (89, 'Cheese - Mix', 54.96);
insert into product (id, name, price) values (90, 'Veal - Striploin', 12.4);
insert into product (id, name, price) values (91, 'Oats Large Flake', 17.71);
insert into product (id, name, price) values (92, 'Ice Cream Bar - Drumstick', 21.91);
insert into product (id, name, price) values (93, 'Mint - Fresh', 79.83);
insert into product (id, name, price) values (94, 'Gooseberry', 98.89);
insert into product (id, name, price) values (95, 'Chevril', 7.9);
insert into product (id, name, price) values (96, 'Wine - White Cab Sauv.on', 77.73);
insert into product (id, name, price) values (97, 'Horseradish Root', 31.52);
insert into product (id, name, price) values (98, 'Wine - White, Ej', 42.86);
insert into product (id, name, price) values (99, 'Chicken - Leg / Back Attach', 77.78);
insert into product (id, name, price) values (100, 'Mushroom - Enoki, Fresh', 50.98);
