insert into section (dtype, id, category, title) values ('section', 101, 'Jewelry', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 102, 'Shoes', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 103, 'Industrial', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 104, 'Music', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 105, 'Garden', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 106, 'Sports', 'Sales');
insert into section (dtype, id, category, title) values ('section', 107, 'Grocery', 'Sales');
insert into section (dtype, id, category, title) values ('section', 108, 'Jewelry', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 109, 'Grocery', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 110, 'Outdoors', 'Support');
insert into section (dtype, id, category, title) values ('section', 111, 'Home', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 112, 'Automotive', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 113, 'Baby', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 114, 'Electronics', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 115, 'Garden', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 116, 'Baby', 'Services');
insert into section (dtype, id, category, title) values ('section', 117, 'Industrial', 'Support');
insert into section (dtype, id, category, title) values ('section', 118, 'Music', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 119, 'Clothing', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 120, 'Books', 'Support');
insert into section (dtype, id, category, title) values ('section', 121, 'Toys', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 122, 'Movies', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 123, 'Electronics', 'Accounting');
insert into section (dtype, id, category, title) values ('section', 124, 'Toys', 'Sales');
insert into section (dtype, id, category, title) values ('section', 125, 'Baby', 'Legal');
insert into section (dtype, id, category, title) values ('section', 126, 'Industrial', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 127, 'Grocery', 'Services');
insert into section (dtype, id, category, title) values ('section', 128, 'Electronics', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 129, 'Health', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 130, 'Tools', 'Training');
insert into section (dtype, id, category, title) values ('section', 131, 'Tools', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 132, 'Tools', 'Training');
insert into section (dtype, id, category, title) values ('section', 133, 'Garden', 'Training');
insert into section (dtype, id, category, title) values ('section', 134, 'Home', 'Sales');
insert into section (dtype, id, category, title) values ('section', 135, 'Clothing', 'Services');
insert into section (dtype, id, category, title) values ('section', 136, 'Grocery', 'Sales');
insert into section (dtype, id, category, title) values ('section', 137, 'Outdoors', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 138, 'Jewelry', 'Sales');
insert into section (dtype, id, category, title) values ('section', 139, 'Books', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 140, 'Home', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 141, 'Electronics', 'Legal');
insert into section (dtype, id, category, title) values ('section', 142, 'Industrial', 'Support');
insert into section (dtype, id, category, title) values ('section', 143, 'Grocery', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 144, 'Home', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 145, 'Home', 'Legal');
insert into section (dtype, id, category, title) values ('section', 146, 'Music', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 147, 'Electronics', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 148, 'Outdoors', 'Services');
insert into section (dtype, id, category, title) values ('section', 149, 'Beauty', 'Legal');
insert into section (dtype, id, category, title) values ('section', 150, 'Toys', 'Support');
insert into section (dtype, id, category, title) values ('section', 151, 'Beauty', 'Training');
insert into section (dtype, id, category, title) values ('section', 152, 'Books', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 153, 'Automotive', 'Legal');
insert into section (dtype, id, category, title) values ('section', 154, 'Music', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 155, 'Sports', 'Legal');
insert into section (dtype, id, category, title) values ('section', 156, 'Industrial', 'Services');
insert into section (dtype, id, category, title) values ('section', 157, 'Tools', 'Support');
insert into section (dtype, id, category, title) values ('section', 158, 'Industrial', 'Training');
insert into section (dtype, id, category, title) values ('section', 159, 'Outdoors', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 160, 'Computers', 'Support');
insert into section (dtype, id, category, title) values ('section', 161, 'Health', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 162, 'Garden', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 163, 'Sports', 'Sales');
insert into section (dtype, id, category, title) values ('section', 164, 'Books', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 165, 'Baby', 'Sales');
insert into section (dtype, id, category, title) values ('section', 166, 'Kids', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 167, 'Industrial', 'Support');
insert into section (dtype, id, category, title) values ('section', 168, 'Health', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 169, 'Garden', 'Services');
insert into section (dtype, id, category, title) values ('section', 170, 'Games', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 171, 'Beauty', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 172, 'Tools', 'Human Resources');
insert into section (dtype, id, category, title) values ('section', 173, 'Games', 'Legal');
insert into section (dtype, id, category, title) values ('section', 174, 'Garden', 'Services');
insert into section (dtype, id, category, title) values ('section', 175, 'Computers', 'Support');
insert into section (dtype, id, category, title) values ('section', 176, 'Music', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 177, 'Clothing', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 178, 'Jewelry', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 179, 'Garden', 'Legal');
insert into section (dtype, id, category, title) values ('section', 180, 'Electronics', 'Training');
insert into section (dtype, id, category, title) values ('section', 181, 'Garden', 'Sales');
insert into section (dtype, id, category, title) values ('section', 182, 'Shoes', 'Engineering');
insert into section (dtype, id, category, title) values ('section', 183, 'Grocery', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 184, 'Grocery', 'Services');
insert into section (dtype, id, category, title) values ('section', 185, 'Clothing', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 186, 'Jewelry', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 187, 'Tools', 'Sales');
insert into section (dtype, id, category, title) values ('section', 188, 'Jewelry', 'Services');
insert into section (dtype, id, category, title) values ('section', 189, 'Clothing', 'Accounting');
insert into section (dtype, id, category, title) values ('section', 190, 'Grocery', 'Legal');
insert into section (dtype, id, category, title) values ('section', 191, 'Music', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 192, 'Outdoors', 'Marketing');
insert into section (dtype, id, category, title) values ('section', 193, 'Jewelry', 'Business Development');
insert into section (dtype, id, category, title) values ('section', 194, 'Beauty', 'Legal');
insert into section (dtype, id, category, title) values ('section', 195, 'Tools', 'Research and Development');
insert into section (dtype, id, category, title) values ('section', 196, 'Garden', 'Services');
insert into section (dtype, id, category, title) values ('section', 197, 'Baby', 'Services');
insert into section (dtype, id, category, title) values ('section', 198, 'Electronics', 'Product Management');
insert into section (dtype, id, category, title) values ('section', 199, 'Music', 'Accounting');
insert into section (dtype, id, category, title) values ('section', 200, 'Jewelry', 'Legal');
